/**
 * Static model catalog.
 * This file is manually maintained. Run `bun run generate-models` to auto-generate
 * from an upstream source when available.
 */
import type { Model } from "./protocol";

export const MODELS: Record<string, Record<string, Model>> = {
  anthropic: {
    "claude-sonnet-4-20250514": {
      id: "claude-sonnet-4-20250514",
      name: "Claude Sonnet 4",
      protocol: "anthropic-messages",
      provider: "anthropic",
      baseUrl: "https://api.anthropic.com",
      reasoning: true,
      input: ["text", "image"],
      cost: { input: 3, output: 15, cacheRead: 0.3, cacheWrite: 3.75 },
      contextWindow: 200000,
      maxTokens: 16000,
    },
    "claude-opus-4-20250514": {
      id: "claude-opus-4-20250514",
      name: "Claude Opus 4",
      protocol: "anthropic-messages",
      provider: "anthropic",
      baseUrl: "https://api.anthropic.com",
      reasoning: true,
      input: ["text", "image"],
      cost: { input: 15, output: 75, cacheRead: 1.5, cacheWrite: 18.75 },
      contextWindow: 200000,
      maxTokens: 32000,
    },
    "claude-haiku-4-20250514": {
      id: "claude-haiku-4-20250514",
      name: "Claude Haiku 4",
      protocol: "anthropic-messages",
      provider: "anthropic",
      baseUrl: "https://api.anthropic.com",
      reasoning: false,
      input: ["text", "image"],
      cost: { input: 0.8, output: 4, cacheRead: 0.08, cacheWrite: 1 },
      contextWindow: 200000,
      maxTokens: 8192,
    },
  },
  openai: {
    "gpt-4o": {
      id: "gpt-4o",
      name: "GPT-4o",
      protocol: "openai-completions",
      provider: "openai",
      baseUrl: "https://api.openai.com/v1",
      reasoning: false,
      input: ["text", "image"],
      cost: { input: 2.5, output: 10, cacheRead: 1.25, cacheWrite: 0 },
      contextWindow: 128000,
      maxTokens: 16384,
    },
    "gpt-4o-mini": {
      id: "gpt-4o-mini",
      name: "GPT-4o Mini",
      protocol: "openai-completions",
      provider: "openai",
      baseUrl: "https://api.openai.com/v1",
      reasoning: false,
      input: ["text", "image"],
      cost: { input: 0.15, output: 0.6, cacheRead: 0.075, cacheWrite: 0 },
      contextWindow: 128000,
      maxTokens: 16384,
    },
    "o3": {
      id: "o3",
      name: "o3",
      protocol: "openai-responses",
      provider: "openai",
      baseUrl: "https://api.openai.com/v1",
      reasoning: true,
      input: ["text", "image"],
      cost: { input: 2, output: 8, cacheRead: 0.5, cacheWrite: 0 },
      contextWindow: 200000,
      maxTokens: 100000,
    },
    "o4-mini": {
      id: "o4-mini",
      name: "o4-mini",
      protocol: "openai-responses",
      provider: "openai",
      baseUrl: "https://api.openai.com/v1",
      reasoning: true,
      input: ["text", "image"],
      cost: { input: 1.1, output: 4.4, cacheRead: 0.275, cacheWrite: 0 },
      contextWindow: 200000,
      maxTokens: 100000,
    },
    "gpt-4.1": {
      id: "gpt-4.1",
      name: "GPT-4.1",
      protocol: "openai-completions",
      provider: "openai",
      baseUrl: "https://api.openai.com/v1",
      reasoning: false,
      input: ["text", "image"],
      cost: { input: 2, output: 8, cacheRead: 0.5, cacheWrite: 0 },
      contextWindow: 1047576,
      maxTokens: 32768,
    },
    "gpt-4.1-mini": {
      id: "gpt-4.1-mini",
      name: "GPT-4.1 Mini",
      protocol: "openai-completions",
      provider: "openai",
      baseUrl: "https://api.openai.com/v1",
      reasoning: false,
      input: ["text", "image"],
      cost: { input: 0.4, output: 1.6, cacheRead: 0.1, cacheWrite: 0 },
      contextWindow: 1047576,
      maxTokens: 32768,
    },
  },
  deepseek: {
    "deepseek-chat": {
      id: "deepseek-chat",
      name: "DeepSeek V3",
      protocol: "openai-completions",
      provider: "deepseek",
      baseUrl: "https://api.deepseek.com/v1",
      reasoning: false,
      input: ["text"],
      cost: { input: 0.27, output: 1.1, cacheRead: 0.07, cacheWrite: 0 },
      contextWindow: 64000,
      maxTokens: 8192,
    },
    "deepseek-reasoner": {
      id: "deepseek-reasoner",
      name: "DeepSeek R1",
      protocol: "openai-completions",
      provider: "deepseek",
      baseUrl: "https://api.deepseek.com/v1",
      reasoning: true,
      input: ["text"],
      cost: { input: 0.55, output: 2.19, cacheRead: 0.14, cacheWrite: 0 },
      contextWindow: 64000,
      maxTokens: 8192,
    },
  },
  openrouter: {
    "anthropic/claude-sonnet-4": {
      id: "anthropic/claude-sonnet-4",
      name: "Claude Sonnet 4 (OpenRouter)",
      protocol: "openai-completions",
      provider: "openrouter",
      baseUrl: "https://openrouter.ai/api/v1",
      reasoning: true,
      input: ["text", "image"],
      cost: { input: 3, output: 15, cacheRead: 0.3, cacheWrite: 0 },
      contextWindow: 200000,
      maxTokens: 16000,
    },
  },
};
